SET local check_function_bodies = off;

CREATE EXTENSION "http" SCHEMA "public";

CREATE TABLE "public"."Supplier_Database" (
  "Name"                 text                     NOT NULL,
  "Type"                 text,
  "Building"             text,
  "Floor"                bigint                   DEFAULT '1'::bigint,
  "Location Description" text                     DEFAULT ''::text,
  "Latitude"             numeric(9,6),
  "Longitude"            numeric(9,6),
  "StartingTime"         text                     DEFAULT 'NA'::text,
  "ClosingTime"          text                     DEFAULT 'NA'::text,
  "ImageURL"             text,
  "id"                   bigint                   GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."Supplier_Database_Supplier_ID_seq") NOT NULL,
  "deleted_at"           timestamp with time zone,
  "created_at"           timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"           timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "Supplier_Database_pkey" PRIMARY KEY (id),
  CONSTRAINT "lat_range" CHECK ((("Latitude" >= ('-90'::integer)::numeric) AND ("Latitude" <= (90)::numeric))),
  CONSTRAINT "lng_range" CHECK ((("Longitude" >= ('-180'::integer)::numeric) AND ("Longitude" <= (180)::numeric))),
  CONSTRAINT "name_length" CHECK (((length(btrim("Name")) >= 1) AND (length(btrim("Name")) <= 100)))
);

ALTER TABLE "public"."Supplier_Database"
  ENABLE ROW LEVEL SECURITY;


CREATE TYPE "public"."supplier_category" AS ENUM (
  'food/coffee',
  'food',
  'printing',
  'shopping',
  'other'
);

CREATE INDEX idx_supplier_deleted_at ON public."Supplier_Database" USING btree (deleted_at);

-- Add a persistent tsvector column that automatically updates on inserts/updates
ALTER TABLE "public"."Supplier_Database"
ADD COLUMN fts tsvector 
GENERATED ALWAYS AS (to_tsvector('english',  "Name"  || ' ' || "Building" || ' ' || "Location Description")) STORED;

CREATE INDEX posts_fts_idx ON "Supplier_Database" USING gin (fts); --gin index

COMMENT ON EXTENSION "http" IS 'HTTP client for PostgreSQL, allows web page retrieval inside the database.';

COMMENT ON TABLE "public"."Supplier_Database" IS 'A list of suppliers in NUS with unique supplier ID, location, building name, floor, description';

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."Supplier_Database" TO "anon", "authenticated", "postgres", "service_role";

GRANT USAGE ON TYPE "public"."supplier_category" TO "postgres";

